version: "3"
services:
  app:
    build:
      context: .
    env_file:
      - app.env
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app:cached
    ports:
      - '3000:3000'
    # command: sh -c "yarn run dev"
    command: sh -c "bash"
    tty: true
    stdin_open: true